[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']
hook_add = '''
  source ~/.config/nvim/plugins/defx.rc.vim
'''

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  syntax enable
  au MyAutoCmd VimEnter * nested colorscheme iceberg
  colorscheme iceberg
  set background=dark
  " 24-bit colorの有効化
  set termguicolors
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline#extensions#tabline#enabled=1
  let g:airline#extensions#tabline#left_sep=' '
  let g:airline#extensions#tabline#left_alt_sep='|'
'''
[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
  let g:airline_theme='iceberg'
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
rev = "release"

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
    source ~/.config/nvim/plugins/denite.rc.vim
'''

[[plugins]]
repo = 'jiangmiao/auto-pairs'

